spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1027030038834358
            client-secret: 1f116b7f3b20f253c9d1b1f5a260cf3f
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - public_profile
              - email
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v12.0/dialog/oauth
            token-uri: https://graph.facebook.com/v12.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
            user-name-attribute: id
server:
  port: 8080